In [5]:
import pandas as pd
import numpy as np
import hashlib as hl
import matplotlib.pyplot as plt
%matplotlib inline

### Loading the Data File:

In [6]:
data = pd.read_csv('/Users/narayani/Desktop/IIITB/Sem6/ML/ML_Project/Housing_Linear Regression/data/housing.csv')
#data.head()

In [7]:
'''def splitTrainData(total_data, ratio):
    indices_Shuffled = np.random.permutation(len(total_data))
    test_data_size = int(len(total_data)* ratio)
    indices_Test = indices_Shuffled[:test_data_size]
    indices_Train = indices_Shuffled[test_data_size:]
    return total_data.iloc[indices_Train], total_data.iloc[indices_Test]
training_data, test_data = splitTrainData(data, 0.3)'''

#Splitting the whole data into training set and test set.

from sklearn.model_selection import train_test_split
training_set, test_set = train_test_split(data,test_size=0.2,random_state = 42)
#print("Train: ",len(train_set), " +  Test: " , len(test_set))

In [8]:

# X_training = training_data.drop(['median_house_value', 'ocean_proximity'],axis =1)
# Y_labels = training_data["median_house_value"].copy()

# from sklearn.preprocessing import Imputer
# imputer = Imputer(strategy = "median")

# imputer.fit(X_training)
# #imputer.statistics_
# #X_training.median().values

# X_imp = imputer.transform(X_training)
# X_inp = pd.DataFrame(X_imp, columns = X_training.columns)

# X_data = X_inp.as_matrix()
# Y = Y_labels.as_matrix()

# X = np.c_[np.ones((len(X_inp),1)),X_data]
# #X= (X - X.mean())/(X+X.std())
# theta = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(Y)

# theta

### Pre-Process the data:
                To remove "NAN-Values" wherever there in the data. And Since, column named "Ocean Proximity" is a text field, we have encode it, so that it can be used for ML-Algorithm.

In [9]:
def preprocessData ( train_set ):
#Removing the target values and copying them as labels/target value for feature values of each data-point.
#new data is the data without the target values
    new_data = train_set.drop("median_house_value", axis = 1)
    labels = train_set["median_house_value"].copy()
    
#Imputer is used to remove all the NAN values in the dataset, but after the removal of the text field i.e "ocean_proximity"
    from sklearn.preprocessing import Imputer
    imputer = Imputer(strategy = "median")  
    ntx_data = new_data.drop("ocean_proximity", axis =1)
    imputer.fit(ntx_data)
    ntx_data_imp = imputer.transform(ntx_data)
    
#Converting into Pandas-Dataframe. 
    ntx_data_inp = pd.DataFrame(ntx_data_imp, columns = ntx_data.columns,index = list(ntx_data.index.values))
    
#Encoding the text-field "ocean_proximity".
    housing_cat = new_data['ocean_proximity']
    from sklearn.preprocessing import OneHotEncoder
    housing_cat_encoded, housing_categories = housing_cat.factorize()
    encoder = OneHotEncoder()
#Reshaping housing_cat_encoder as it is 1-D array, but fit_transform expects a 2-D array.
    housing_cat_1hot =encoder.fit_transform(housing_cat_encoded.reshape(-1,1))
    (housing_cat_1hot.toarray())

    import category_encoders as c_enc
    encoder = c_enc.OneHotEncoder()
    housing_cat_reshaped = housing_cat.values.reshape(-1,1)
    encoder.fit(housing_cat_reshaped)
    
    X_cleaned = encoder.transform(housing_cat_reshaped)
#Converting Encoded values for "ocean_proximity" to matrix
    enc_data = X_cleaned.as_matrix()
    
#Feature Scaling for data without the encoded values for "ocean_proximity":
    from sklearn.preprocessing import StandardScaler
    scaler = StandardScaler()
    scaler.fit(ntx_data_inp)
    data_without_enc = scaler.transform(ntx_data_inp)

#data without encoded values is being appended by the encoded values to get the complete data for computation.
    data_training = np.append(data_without_enc, enc_data, axis = 1)
    data_training = X = np.c_[np.ones((len(data_training),1)),data_training]
    
    
    return data_training, labels  

### Training on the Training Set:

In [10]:
training_data , training_labels = preprocessData(training_set)
testing_data , testing_labels = preprocessData(test_set)
#Hyperparameter
alpha = .1

In [11]:
n = training_data.shape[1]
I = np.identity(n)
I[0,0] = 0
#Matrix in which Identity matrix first element is replaced by 0 instead of 1.
A = I

In [12]:
# from sklearn.linear_model import LinearRegression
# lin_reg = LinearRegression()
# lin_reg.fit(training_data, training_labels)
# lin_reg.predict(training_data)

### Calculating the parameter matrix from Ridge Equation:

In [13]:
#temp = (training_data.T).dottraining_data)
#Calculating Parameters with Ridge Equation.
theta = np.linalg.inv(training_data.T.dot(training_data) + (alpha)*A).dot(training_data.T).dot(training_labels)

theta

array([238252.92341126, -53822.57959311, -54412.58749094,  13890.41026217,
       -13090.60576714,  43065.99923065, -43402.47060121,  18379.81171344,
        75166.34517979, -14920.2688228 , -58140.53857764, -18352.46936135,
       -23486.15567601, 114899.43244337,      0.        ])

### Predicted labels for training data:

In [14]:
train_predicted_Y = training_data.dot(theta.T)
train_predicted_Y

array([188631.70020122, 290380.97260532, 250983.12775868, ...,
       194624.89800017, 281816.41515812, 271570.77765465])

In [15]:
# X_test = test_data.drop(['median_house_value','ocean_proximity'], axis =1)
# Y_actuals = test_data["median_house_value"].copy()

# imputer.fit(X_test)
# X_test_imp = imputer.transform(X_test)
# test_inp = pd.DataFrame(X_test_imp, columns = X_test.columns)

# data_test = test_inp.as_matrix()
# actual_Y = Y_actuals.as_matrix()

# #test_inp.info()
# actual_Y

#test = np.c_[np.ones((len(test_inp)),1),data_test]
#test = np.c_[np.ones((len(test_inp),1)),data_test]
#test



### Predicated labels for test data:

In [16]:
test_predicted_Y = testing_data.dot(theta.T)
test_predicted_Y


array([ 98170.29543207, 168708.04170487, 223012.8749381 , ...,
       444691.3182825 , 166435.90459402, 185545.08820204])

In [17]:
# X_housing = data.drop(['median_house_value', 'ocean_proximity'],axis =1)
# Y_housing = data["median_house_value"].copy()

# imputer.fit(X_housing)

# X_housing_imp = imputer.transform(X_housing)
# X_housing_inp = pd.DataFrame(X_housing_imp, columns = X_housing.columns)

# X_housing_data = X_housing_inp.as_matrix()
# housing_Y = Y_housing.as_matrix()
# housing = np.c_[np.ones((len(X_housing_inp),1)),X_housing_data]



### Training on the Complete Data:

In [18]:
housing_data , housing_labels = preprocessData(data)
n_new = housing_data.shape[1]
I = np.identity(n_new)
I[0,0] = 0
#Matrix 
A_new = I

In [19]:
#Calulating new Parameter Matrix.
theta_new = np.linalg.inv(training_data.T.dot(training_data) + (alpha)*A_new).dot(training_data.T).dot(training_labels)

theta_new

array([238252.92341126, -53822.57959311, -54412.58749094,  13890.41026217,
       -13090.60576714,  43065.99923065, -43402.47060121,  18379.81171344,
        75166.34517979, -14920.2688228 , -58140.53857764, -18352.46936135,
       -23486.15567601, 114899.43244337,      0.        ])

### Predicated labels for whole housing dataset without splitting:

In [20]:
housing_predicted_Y = housing_data.dot(theta_new.T)

housing_predicted_Y

array([420407.95962734, 429613.00912515, 389857.80890539, ...,
        78552.67039523,  89674.73674787, 107124.91700724])

### Root Mean Squared Error :

In [21]:
from sklearn.metrics import mean_squared_error

test_mse = mean_squared_error(testing_labels, test_predicted_Y)
train_mse = mean_squared_error(training_labels,train_predicted_Y)
housing_mse = mean_squared_error(housing_labels, housing_predicted_Y)


print "RMSE for Traning Data: "+ str(np.sqrt(train_mse))
print "RMSE for Test Data: " + str(np.sqrt(test_mse))
print "RMSE for Housing Data taken without splitting: "+ str(np.sqrt(housing_mse))

RMSE for Traning Data: 68433.95200602397
RMSE for Test Data: 75276.69896705075
RMSE for Housing Data taken without splitting: 76958.73383605707
